title: Armando Ortez Bonilla  
description: Don't let anyone rob you of your creativity, or your curosity - Mae Jemison first African American Astronaut
remote_theme: pages-themes/slate

# Enable GitHub Pages plugin
plugins:
  - jekyll-remote-theme
  

# Set navigation order
nav_order: 1

# Add your navigation structure (optional override)
nav:
  - title: "Home"
    url: /
  - title: "About Me"
    url: /about
  - title: "Projects"
    url: /projects
  - title: "Contact"
    url: /contact

# Optional extras
color_scheme: light
logo: /assets/logo.png
search_enabled: true
